version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - devops-network

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge
